version: '3'

services:
  apps:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./graphql-project
        target: /graphql-project

      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mysql:latest
    container_name: mysqllatest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=user
      - PMA_PASSWORD=pass
    ports:
      - "3000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
# volumes:
#   docker/db/data:
#   docker/db/my.cnf:
#   docker/db/sql:
# version: "3"

# services:
#   cli:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 5002:5002
#     tty: true
#     volumes:
#       - type: bind
#         source: ./src
#         target: /src

# volumes:
#   bin:
#   out: